<?php

namespace ContainerAVnWnil;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EmI5tzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EmI5tz_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EmI5tz_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\CategoriesController::getAllCategories' => ['privates', '.service_locator.Xaj__Lx.App\\Controller\\CategoriesController::getAllCategories()', 'getCategoriesControllergetAllCategoriesService', true],
            'App\\Controller\\CategoriesController::deleteCategories' => ['privates', '.service_locator.zA8TQRC.App\\Controller\\CategoriesController::deleteCategories()', 'getCategoriesControllerdeleteCategoriesService', true],
            'App\\Controller\\CategoriesController::createCategories' => ['privates', '.service_locator.XE9Xz04.App\\Controller\\CategoriesController::createCategories()', 'getCategoriesControllercreateCategoriesService', true],
            'App\\Controller\\CategoriesController::updateCategories' => ['privates', '.service_locator.Jmpjl2i.App\\Controller\\CategoriesController::updateCategories()', 'getCategoriesControllerupdateCategoriesService', true],
            'App\\Controller\\ProduitsController::getAllProduits' => ['privates', '.service_locator.G67Y8Do.App\\Controller\\ProduitsController::getAllProduits()', 'getProduitsControllergetAllProduitsService', true],
            'App\\Controller\\ProduitsController::deleteProduits' => ['privates', '.service_locator.fWgX9Lv.App\\Controller\\ProduitsController::deleteProduits()', 'getProduitsControllerdeleteProduitsService', true],
            'App\\Controller\\ProduitsController::createProduits' => ['privates', '.service_locator.Jmpjl2i.App\\Controller\\ProduitsController::createProduits()', 'getProduitsControllercreateProduitsService', true],
            'App\\Controller\\ProduitsController::updateProduits' => ['privates', '.service_locator.lgMK7na.App\\Controller\\ProduitsController::updateProduits()', 'getProduitsControllerupdateProduitsService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\CategoriesController:getAllCategories' => ['privates', '.service_locator.Xaj__Lx.App\\Controller\\CategoriesController::getAllCategories()', 'getCategoriesControllergetAllCategoriesService', true],
            'App\\Controller\\CategoriesController:deleteCategories' => ['privates', '.service_locator.zA8TQRC.App\\Controller\\CategoriesController::deleteCategories()', 'getCategoriesControllerdeleteCategoriesService', true],
            'App\\Controller\\CategoriesController:createCategories' => ['privates', '.service_locator.XE9Xz04.App\\Controller\\CategoriesController::createCategories()', 'getCategoriesControllercreateCategoriesService', true],
            'App\\Controller\\CategoriesController:updateCategories' => ['privates', '.service_locator.Jmpjl2i.App\\Controller\\CategoriesController::updateCategories()', 'getCategoriesControllerupdateCategoriesService', true],
            'App\\Controller\\ProduitsController:getAllProduits' => ['privates', '.service_locator.G67Y8Do.App\\Controller\\ProduitsController::getAllProduits()', 'getProduitsControllergetAllProduitsService', true],
            'App\\Controller\\ProduitsController:deleteProduits' => ['privates', '.service_locator.fWgX9Lv.App\\Controller\\ProduitsController::deleteProduits()', 'getProduitsControllerdeleteProduitsService', true],
            'App\\Controller\\ProduitsController:createProduits' => ['privates', '.service_locator.Jmpjl2i.App\\Controller\\ProduitsController::createProduits()', 'getProduitsControllercreateProduitsService', true],
            'App\\Controller\\ProduitsController:updateProduits' => ['privates', '.service_locator.lgMK7na.App\\Controller\\ProduitsController::updateProduits()', 'getProduitsControllerupdateProduitsService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\CategoriesController::getAllCategories' => '?',
            'App\\Controller\\CategoriesController::deleteCategories' => '?',
            'App\\Controller\\CategoriesController::createCategories' => '?',
            'App\\Controller\\CategoriesController::updateCategories' => '?',
            'App\\Controller\\ProduitsController::getAllProduits' => '?',
            'App\\Controller\\ProduitsController::deleteProduits' => '?',
            'App\\Controller\\ProduitsController::createProduits' => '?',
            'App\\Controller\\ProduitsController::updateProduits' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\CategoriesController:getAllCategories' => '?',
            'App\\Controller\\CategoriesController:deleteCategories' => '?',
            'App\\Controller\\CategoriesController:createCategories' => '?',
            'App\\Controller\\CategoriesController:updateCategories' => '?',
            'App\\Controller\\ProduitsController:getAllProduits' => '?',
            'App\\Controller\\ProduitsController:deleteProduits' => '?',
            'App\\Controller\\ProduitsController:createProduits' => '?',
            'App\\Controller\\ProduitsController:updateProduits' => '?',
        ]);
    }
}
