<?php

namespace ContainerAVnWnil;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoriesControllergetAllCategoriesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Xaj__Lx.App\Controller\CategoriesController::getAllCategories()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Xaj__Lx.App\\Controller\\CategoriesController::getAllCategories()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categoriesRepository' => ['privates', 'App\\Repository\\CategoriesRepository', 'getCategoriesRepositoryService', true],
            'serializer' => ['privates', 'serializer', 'getSerializerService', false],
        ], [
            'categoriesRepository' => 'App\\Repository\\CategoriesRepository',
            'serializer' => '?',
        ]))->withContext('App\\Controller\\CategoriesController::getAllCategories()', $container);
    }
}
