<?php

namespace ContainerAVnWnil;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoriesControllerdeleteCategoriesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zA8TQRC.App\Controller\CategoriesController::deleteCategories()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zA8TQRC.App\\Controller\\CategoriesController::deleteCategories()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categoriesRepository' => ['privates', 'App\\Repository\\CategoriesRepository', 'getCategoriesRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'serializer' => ['privates', 'serializer', 'getSerializerService', false],
        ], [
            'categoriesRepository' => 'App\\Repository\\CategoriesRepository',
            'em' => '?',
            'serializer' => '?',
        ]))->withContext('App\\Controller\\CategoriesController::deleteCategories()', $container);
    }
}
