<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW072Xd2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW072Xd2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerW072Xd2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerW072Xd2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerW072Xd2\App_KernelDevDebugContainer([
    'container.build_hash' => 'W072Xd2',
    'container.build_id' => '3cf2e074',
    'container.build_time' => 1733135904,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW072Xd2');
