<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXOeUDwI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXOeUDwI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXOeUDwI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXOeUDwI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXOeUDwI\App_KernelDevDebugContainer([
    'container.build_hash' => 'XOeUDwI',
    'container.build_id' => '12664ed0',
    'container.build_time' => 1733063444,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXOeUDwI');
