<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'categories' => [[], ['_controller' => 'App\\Controller\\CategoriesController::getAllCategories'], [], [['text', '/api/categories']], [], [], []],
    'deleteCategories' => [['id'], ['_controller' => 'App\\Controller\\CategoriesController::deleteCategories'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/categories']], [], [], []],
    'app_produits' => [[], ['_controller' => 'App\\Controller\\ProduitsController::getAllProduits'], [], [['text', '/api/produits']], [], [], []],
    'App\Controller\CategoriesController::getAllCategories' => [[], ['_controller' => 'App\\Controller\\CategoriesController::getAllCategories'], [], [['text', '/api/categories']], [], [], []],
    'App\Controller\CategoriesController::deleteCategories' => [['id'], ['_controller' => 'App\\Controller\\CategoriesController::deleteCategories'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/categories']], [], [], []],
    'App\Controller\ProduitsController::getAllProduits' => [[], ['_controller' => 'App\\Controller\\ProduitsController::getAllProduits'], [], [['text', '/api/produits']], [], [], []],
];
