<?php

namespace Container3aLE29J;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProduitsControllerupdateProduitsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lgMK7na.App\Controller\ProduitsController::updateProduits()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lgMK7na.App\\Controller\\ProduitsController::updateProduits()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'serializer' => ['privates', 'serializer', 'getSerializerService', false],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'produitsRepository' => ['privates', 'App\\Repository\\ProduitsRepository', 'getProduitsRepositoryService', true],
            'categoriesRepository' => ['privates', 'App\\Repository\\CategoriesRepository', 'getCategoriesRepositoryService', true],
        ], [
            'serializer' => '?',
            'em' => '?',
            'produitsRepository' => 'App\\Repository\\ProduitsRepository',
            'categoriesRepository' => 'App\\Repository\\CategoriesRepository',
        ]))->withContext('App\\Controller\\ProduitsController::updateProduits()', $container);
    }
}
