<?php

namespace Container3aLE29J;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProduitsControllercreateProduitsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Jmpjl2i.App\Controller\ProduitsController::createProduits()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Jmpjl2i.App\\Controller\\ProduitsController::createProduits()'] = ($container->privates['.service_locator.Jmpjl2i'] ?? $container->load('get_ServiceLocator_Jmpjl2iService'))->withContext('App\\Controller\\ProduitsController::createProduits()', $container);
    }
}
