<?php

namespace ContainerW072Xd2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoriesControllercreateCategoriesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XE9Xz04.App\Controller\CategoriesController::createCategories()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XE9Xz04.App\\Controller\\CategoriesController::createCategories()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'serializer' => ['privates', 'serializer', 'getSerializerService', false],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'serializer' => '?',
            'em' => '?',
        ]))->withContext('App\\Controller\\CategoriesController::createCategories()', $container);
    }
}
