<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP00i4gF\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP00i4gF/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerP00i4gF.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerP00i4gF\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerP00i4gF\App_KernelProdContainer([
    'container.build_hash' => 'P00i4gF',
    'container.build_id' => '3a90be05',
    'container.build_time' => 1733252433,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerP00i4gF');
