<?php

namespace ContainerP00i4gF;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProduitsControllerdeleteProduitsService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.fWgX9Lv.App\Controller\ProduitsController::deleteProduits()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fWgX9Lv.App\\Controller\\ProduitsController::deleteProduits()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'produitsRepository' => ['privates', 'App\\Repository\\ProduitsRepository', 'getProduitsRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'produitsRepository' => 'App\\Repository\\ProduitsRepository',
            'em' => '?',
        ]))->withContext('App\\Controller\\ProduitsController::deleteProduits()', $container);
    }
}
