<?php

namespace ContainerP00i4gF;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProduitsControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\ProduitsController' shared autowired service.
     *
     * @return \App\Controller\ProduitsController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\ProduitsController'] = $instance = new \App\Controller\ProduitsController();

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\ProduitsController', $container));

        return $instance;
    }
}
